// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ver2PageTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ver2PageTags));
        
        string IMigrationMetadata.Id
        {
            get { return "202212171733539_Ver-2-PageTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
